
# Site settings
title: Wanjie Li
name: Wanjie Li
subtitle:  Ph.D Candidate
email: li_wanjie1014@stu.scu.edu.cn
description: >
   Ph.D Candidate
baseurl: ""
url: "https://Li-Wanjie.github.io/"
github_username:  Li-Wanjie
disqus_baseurl: "https://Li-Wanjie.github.io/"
disqus_shortname: https-Li-Wanjie-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Wanjie Li"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: Wanjie Li
    url: https://github.com/Li-Wanjie
    desc: Fork me on GitHub
    share: false

  - name: ORCiD
    icon: ORCiD
    username: Wanjie Li
    url: https://orcid.org/0000-0001-7175-7287
    desc: Connect with me on ORCiD
    share: true
